apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  namespace: defauly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
        - name: influxdb
          image: influxdb:1.7.9
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: influxdb
  name: influxdb
  namespace: influxdb
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 8086
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: influxdb
  sessionAffinity: None
  type: NodePort
